# conda env create|update --file environment.yml
name: prot-met
dependencies:
- python=3.6
- pip
- pip:
  - '--editable=.'
  - flake8
  - flake8-quotes
  - jupyter
  - matplotlib
  - numpy==1.16.
  - pandas==0.24.1
  - pytest
  - pytest-mock
  - scipy
  - seaborn
  - sklearn
  - torch
  - imageio
  - scikit-image
